/* eslint-disable */
// AUTO-GENERATED by scripts/build-chat-knowledge.mjs — do not edit by hand.
// Re-run: npm run chat:knowledge

export type GeneratedChatService = {
  name: string;
  path: string;
  summary: string;
  details?: string;
};

export const GENERATED_CHAT_SERVICES: GeneratedChatService[] = [
  {
    "name": "Enfermería",
    "path": "/services/enfermeria",
    "summary": "Cuidado profesional y humanizado.",
    "details": "En Bihospharma IPS, nuestro equipo de enfermería está comprometido con tu bienestar, ofreciendo atención profesional, humana y oportuna en cada procedimiento y acompañamiento que necesites. Incluye: Toma de signos vitales.; Administración de medicamentos por vía oral, intramuscular, endovenosa y subcutánea.; Curaciones y cuidado de heridas.; Retiro y cambio de puntos de sutura.; Canalización de vías periféricas.; Nebulizaciones y terapias respiratorias.; Control de glicemia capilar.; Aplicación de inyectables y vacunas.."
  },
  {
    "name": "Fisioterapia",
    "path": "/services/fisioterapia",
    "summary": "Rehabilitación y recuperación funcional.",
    "details": "En Bihospharma IPS ofrecemos Fisioterapia para prevenir, tratar y rehabilitar lesiones y disfunciones musculoesqueléticas. Nuestro objetivo es aliviar el dolor, recuperar tu movilidad y ayudarte a retomar tus actividades con seguridad. Incluye: Terapia manual y movilización articular.; Ejercicio terapéutico y fortalecimiento.; Rehabilitación postoperatoria y postlesión.; Manejo del dolor agudo y crónico.; Fisioterapia respiratoria.; Prevención de lesiones y educación postural.; Mejora de la movilidad y la fuerza.; Disminución del dolor y la inflamación.."
  },
  {
    "name": "Medicina General",
    "path": "/services/medicina-general",
    "summary": "Atención integral para prevención, diagnóstico y tratamiento con enfoque humano.",
    "details": "En Bihospharma, ofrecemos atención en Medicina General con un enfoque integral en la prevención, diagnóstico y tratamiento de enfermedades. Nuestro equipo de profesionales está comprometido con tu salud, brindándote un servicio cálido, confiable y personalizado. Incluye: Fiebre persistente, tos o síntomas gripales prolongados.; Dolor de cabeza frecuente, mareos o fatiga extrema.; Malestar digestivo recurrente o alteraciones en la alimentación.; Problemas en la piel como irritaciones, alergias o infecciones.; Control y seguimiento de enfermedades crónicas.; Revisión médica general para preve…"
  },
  {
    "name": "Medicina Interna",
    "path": "/services/medicina-interna",
    "summary": "Atención especializada en enfermedades del adulto.",
    "details": "En Bihospharma IPS, contamos con médicos especialistas en Medicina Interna dedicados a la prevención, diagnóstico y tratamiento de enfermedades en adultos, brindando atención humana, ética y de alta calidad. Incluye: Hipertensión arterial y enfermedades cardiovasculares.; Diabetes y trastornos endocrinos.; Enfermedades respiratorias crónicas.; Trastornos gastrointestinales y hepáticos.; Enfermedades autoinmunes.; Alteraciones del sistema inmune.; Valoración integral de pacientes con múltiples enfermedades.; Evaluación médica integral.."
  },
  {
    "name": "Medicina Laboral",
    "path": "/services/medicina-laboral",
    "summary": "Exámenes ocupacionales y salud en el trabajo.",
    "details": "En Bihospharma S.A.S, ofrecemos un servicio integral de Medicina Laboral, enfocado en la prevención, diagnóstico y control de riesgos ocupacionales. Nuestro objetivo es garantizar el bienestar de los trabajadores y el cumplimiento de las normativas de salud laboral en las empresas. Incluye: Riesgos osteomusculares y de fatiga laboral.; Exposición a agentes físicos, químicos o biológicos.; Trastornos respiratorios y de la voz por el trabajo.; Reintegro y restricciones laborales.; Evaluación médica integral.; Diagnóstico preciso y personalizado.; Coordinación con otras especialidades.; Atenci…"
  },
  {
    "name": "Nutrición",
    "path": "/services/nutricion",
    "summary": "Asesoría nutricional personalizada.",
    "details": "En Bihospharma IPS, nuestro servicio de nutrición está enfocado en mejorar tu calidad de vida a través de planes alimenticios personalizados, adaptados a tus necesidades, condición de salud y estilo de vida. Incluye: Control y manejo de peso.; Alimentación en enfermedades crónicas (diabetes, hipertensión, colesterol alto).; Nutrición deportiva.; Planes para embarazo y lactancia.; Alimentación en la infancia y adolescencia.; Educación nutricional para hábitos saludables.; Valoración integral y personalizada.; Planes alimenticios prácticos y adaptados a tu rutina.."
  },
  {
    "name": "Psicología",
    "path": "/services/psicologia",
    "summary": "Apoyo psicológico para el bienestar emocional.",
    "details": "En Bihospharma IPS ofrecemos acompañamiento en Psicología Clínica, brindando un espacio seguro y confidencial para el cuidado de tu salud mental, ayudándote a comprender, manejar y superar situaciones que afectan tu vida diaria. Incluye: Estrés, ansiedad y depresión.; Trastornos del sueño.; Manejo del duelo.; Terapia individual, de pareja y familiar.; Orientación en problemas de conducta y aprendizaje en niños y adolescentes.; Desarrollo de habilidades sociales y emocionales.; Promoción de la salud mental y prevención de recaídas.; Atención personalizada y confidencial.."
  },
  {
    "name": "Reumatología",
    "path": "/services/reumatologia",
    "summary": "Diagnóstico y tratamiento de enfermedades reumáticas.",
    "details": "En Bihospharma IPS, contamos con especialistas en Reumatología dedicados a la prevención, diagnóstico y tratamiento de enfermedades que afectan el sistema musculoesquelético y el tejido conectivo, mejorando tu calidad de vida y movilidad. Incluye: Artritis reumatoide.; Artrosis.; Lupus eritematoso sistémico.; Espondiloartritis.; Gota.; Osteoporosis.; Síndrome de Sjögren.; Fibromialgia.."
  },
  {
    "name": "Trabajo Social",
    "path": "/services/trabajo-social",
    "summary": "Acompañamiento social en salud.",
    "details": "En Bihospharma IPS, el área de Trabajo Social acompaña a los usuarios y sus familias en la resolución de situaciones sociales, familiares y comunitarias que afectan su salud y calidad de vida. Incluye: Orientación familiar y comunitaria.; Acompañamiento en situaciones de vulnerabilidad social.; Asesoría en acceso a programas y servicios de salud.; Prevención de problemáticas sociales que afectan la salud.; Promoción de hábitos saludables y redes de apoyo.; Fortalecimiento de la comunicación y relaciones familiares.; Atención cercana, humana y empática.; Orientación integral frente a situaci…"
  }
];
