-- Horarios y pausa de almuerzo
ALTER TABLE "User" ADD COLUMN "workStart" TEXT NOT NULL DEFAULT '07:30';
ALTER TABLE "User" ADD COLUMN "morningEnd" TEXT NOT NULL DEFAULT '13:00';
ALTER TABLE "User" ADD COLUMN "lunchStart" TEXT NOT NULL DEFAULT '13:00';
ALTER TABLE "User" ADD COLUMN "lunchEnd" TEXT NOT NULL DEFAULT '14:00';
ALTER TABLE "User" ADD COLUMN "workEnd" TEXT NOT NULL DEFAULT '17:30';
ALTER TABLE "User" ADD COLUMN "satWorkStart" TEXT;
ALTER TABLE "User" ADD COLUMN "satWorkEnd" TEXT;

ALTER TABLE "Shift" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'active';
ALTER TABLE "Shift" ADD COLUMN "lunchStartedAt" DATETIME;
ALTER TABLE "Shift" ADD COLUMN "lunchEndedAt" DATETIME;
